
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pet_registry_development

test:
  <<: *default
  database: pet_registry_test

production:
  <<: *default
  database: pet_registry_production
  username: pet_registry
  password: <%= ENV["PET_REGISTRY_DATABASE_PASSWORD"] %>
