test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudinary:
  service: Cloudinary
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_secret) %>
  overwrite: true
  invalidate: true

cloudinary_reports:
  service: Cloudinary
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_secret) %>
  folder: <%= Rails.env %>/reports
  overwrite: true
  invalidate: true

cloudinary_pets:
  service: Cloudinary
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, Rails.env.to_sym, :api_secret) %>
  folder: <%= Rails.env %>/pets
  overwrite: true
  invalidate: true
